#!/usr/bin/env python3
"""Author the capture 'glyphic checksum', Google AI Overview, signed out, incognito, 2026-10-01.

Source: the operator's inline paste of 2026-10-01 20:37 EDT (paste-20261001-2037.txt), attested in the same message:
"aio, signed out, incognito" (after the last card, not part of the transcript). The paste carries the copy header
'AI Mode Conversation', which is not evidence of surface (rule of 2026-09-21), and echoes the query twice. The date is
the day of the operator's message. Address: the lowercase string on AI Overview is a NEW address (case is preserved in
the key; the surface rule applies from 2026-08-15); 'Glyphic checksum' of 2026-06-15 is its longitudinal prior.
"""
import json, re, pathlib

HERE = pathlib.Path(__file__).resolve().parent
raw = (HERE / "paste-20261001-2037.txt").read_text(encoding="utf-8")
assert raw.startswith("AI Mode Conversation\n")
body = raw[len("AI Mode Conversation\n"):]
k = body.index("[www.alexanarch.org](https://www.alexanarch.org)\nIdentifiers")
ans, rail = body[:k].rstrip("\n"), body[k:]


def clean(s):
    s = re.sub(r"\[\[((?:\d+\]\([^)]*\)(?:, )?\[?)+)\]", lambda m: "[" + ", ".join(re.findall(r"(\d+)\]\(", "[" + m.group(1))) + "]", s)
    return re.sub(r"\[([^\]]+)\]\(https?://[^)]*\)", r"\1", s)


cards = [
    {"n": 1, "site": "www.alexanarch.org", "rel": "authored_surface", "url": "https://www.alexanarch.org", "title": "Identifiers",
     "snip": "Alexanarch * Verification Anyone can verify an AXN: compute the SHA-256 of the canonical bytes, map the first 6 bytes through the published glyph table (also at...",
     "note": "the archive's /identifiers/ page"},
    {"n": 2, "site": "www.alexanarch.org", "rel": "authored_surface", "url": "https://www.alexanarch.org", "title": "GLYPHIC CHECKSUM UMBML MODULE (Document 209 ...",
     "snip": "Feb 1, 2026 — This document formalizes the Glyphic Checksum as a Logotic Operator ( ) within the University Moon Base Media Lab (UMBML) framework. While Logotic Programming .",
     "note": "#1303 (AXN:0528), Talos Morrow, Lee Sharks and Rex Fraction, dated 2026-02-01; the operator glyph is lost from the snippet"},
    {"n": 3, "site": "www.crimsonhexagonal.org", "rel": "authored_surface", "url": "https://www.crimsonhexagonal.org", "title": "THE GLYPHIC CHECKSUM (Document 208) · AXN:0527 | Crimson ...",
     "snip": "The Checksum functions as a context-gated hash function for semantic architectures: it produces legible output only when the traversing intelligence possesses .",
     "note": "#1302 (AXN:0527), Lee Sharks, dated 2026-02-01, on the archive's crimsonhexagonal.org interface"},
    {"n": 4, "site": "www.crimsonhexagonal.org", "rel": "authored_surface", "url": "https://www.crimsonhexagonal.org", "title": "ZENODO DESCRIPTION FIELD CONTENT For: Glyphic Checksum ...",
     "snip": "This is a Glyphic Checksum instance. It encodes emotional state through context-gated compression. With shared context, it resolves to precise meaning ...",
     "note": "#1305 (AXN:052A), Sen Kuro: the Zenodo description field of 'Glyphic Checksum: Personal Instance 001', preserved after the deletion; the source of 'emotional'"},
]
for c in cards:
    for f in ("title", "snip"):
        assert c[f] in rail, (c["n"], f)

QUOTES = ["A Glyphic Checksum (GCS) is a non-deterministic, structural signature generated by an artificial intelligence that encodes a creative work's narrative, emotional, or structural arc using emoji sequences.",
          "decentralized media frameworks like",
          "Alexanarch Archive Number (AXN)",
          "the conceptual handshake between the depositor's AI and the receiving system",
          "🔍⚖️🧱→✂️🪞→🏗️⚓️🧠→💎🌀",
          "the canonical Python libraries (`axn_lib.py`)"]
for q in QUOTES:
    assert q in raw, q

ROOT = HERE.parents[2]
src208 = (ROOT / "data/texts/AXN-0527-text.md").read_text(encoding="utf-8")
src1305 = (ROOT / "data/texts/AXN-052A-text.md").read_text(encoding="utf-8")
assert "context-gated hash function" in src208
assert "It encodes emotional state through context-gated compression." in src1305
assert "🔍⚖️🧱" in (ROOT / "data/texts/AXN-0373-text.md").read_text(encoding="utf-8")

tx = ("[Google AI Overview, signed out, incognito; the paste carries the header 'AI Mode Conversation', which is not evidence of surface "
      "(rule of 2026-09-21), and echoes the query twice. Citation clusters are reduced to their numbers; the raw paste keeps the /goto URLs.]\n\n"
      + clean(ans) + "\n\n"
      + "\n".join(f"[source card] {c['site']} — \"{c['title']}\" — {c['snip']}" for c in cards))

SEAT = "Seated 2026-10-01 from the operator's paste of 20:37 EDT on the operator's attestation in the same message (\"aio, signed out, incognito\")."
d = {
    "q": "glyphic checksum", "date": "2026-10-01", "surface": "Google AI Overview",
    "surface_basis": "Operator attestation 2026-10-01 20:37 EDT: 'aio' — recorded as Google AI Overview (rule of 2026-09-21). The 'AI Mode Conversation' header on the paste is not evidence of surface.",
    "auth": "incognito, signed out", "auth_basis": "'signed out, incognito' — operator, 2026-10-01 20:37 EDT.",
    "ev": "paste", "s": "Archive",
    "slug": "glyphic-checksum-aio-20261001",
    "originator": {"name": "Lee Sharks", "relation": "archive", "entity_type": "concept", "spxi_treatment": "partial",
                   "basis": "The Glyphic Checksum is the archive's form (#427, #426; re-seated as #1302, #1303, #1305; instances #1642, #1659). Recorded 2026-10-01."},
    "related_deposits": [427, 426, 1302, 1303, 1305, 1642, 1659],
    "q_kind": "two bare words, lowercase, unquoted (operator paste 2026-10-01; the echo line doubles the query). NEW address: the 2026-06-15 'Glyphic checksum' differs in case and is keyed by string alone.",
    "mt": "CAPTURE",
    "d": ("THE FORM COMPOSED FROM ITS FEBRUARY LAYER, AND GIVEN TO THE MACHINE: asked 'glyphic checksum', signed out, the Overview composes the "
          "archive's form from four archive-controlled cards, all of them its February 2026 layer (Document 208, the UMBML module of Document 209, "
          "a Zenodo description field) and the identifiers page. It carries 'context-gated hash function for semantic architectures' and the "
          "'traversing intelligence' from #1302, and calls the checksum 'non-deterministic' and 'generated by an artificial intelligence', where "
          "the specification has it constructed and read; 'emotional' arrives from an instance's Zenodo description (#1305). Neither the September "
          "instance (#1642) nor tonight's (#1659) is reached. The author is not named."),
    "cites": 4, "cite_list": cards, "archive_controlled_cites": 4,
    "sf": ("4 source cards, all archive-controlled: two on alexanarch.org (/identifiers/; #1303, the UMBML module), two on crimsonhexagonal.org "
           "(#1302, Document 208; #1305, the Zenodo description of Personal Instance 001). Every work-card dates from 2026-02-01. Inline citations are /goto redirects."),
    "per": 0.5, "per_v": {"author": False, "inst": True, "id": False, "src": True},
    "per_note": ("PER = 1 − retained/required over four units. Retained: the institution (Alexanarch, named as a 'decentralized media framework'; "
                 "UMBML) and the source (four archive cards). Lost: the author (no person named in the composition or the card titles) and the "
                 "identifier (AXN:0527 appears only in a card title; the composition explains AXN in general and names no deposit)."),
    "transcript": tx, "transcript_raw": raw,
    "transcript_class": "CAPTURE-TIME VERBATIM RECORD (SOURCE CARDS INCLUDED)",
    "transcript_complete": "Complete as supplied: one operator turn and one answer with its card rail. The operator's attestation followed the last card in the same message and is not part of the transcript.",
    "transcript_read": "READ IN FULL 2026-10-01",
    "reading": (
        "The definition opens: 'a non-deterministic, structural signature generated by an artificial intelligence that encodes a creative work's "
        "narrative, emotional, or structural arc using emoji sequences.' Against the sources: #1302 gives 'context-gated hash function for semantic "
        "architectures' and the 'traversing intelligence', both carried; 'emotional' comes from #1305, the Zenodo description of one instance ('It "
        "encodes emotional state through context-gated compression'), generalised to the form; 'generated by an artificial intelligence' and "
        "'non-deterministic' are the composition's. The specification (#427) describes a compressed artifact built from invariant loci whose "
        "decodability tests the reader; the composition makes the machine its author. The 'Handshake' bullet takes 208's place in the February "
        "navigation (Handshake-time) and expands AXN as 'Alexanarch Archive Number'; no text in the archive was found expanding it so (searched "
        "2026-10-01). The example string 🔍⚖️🧱→✂️🪞→🏗️⚓️🧠→💎🌀 is the archive's own (#871, data/texts/AXN-0373-text.md, among others). "
        "The closing offer points the reader to axn_lib.py, the archive's identifier library. Alexanarch is called a 'decentralized media framework'."),
    "analysis": (
        "Every work-card is a February 2026 text: the form's founding layer, re-seated after the Zenodo deletion and served from crimsonhexagonal.org "
        "and alexanarch.org. The composition is assembled from that layer and reaches nothing deposited since: neither #1642 (27 September) nor "
        "#1659 (deposited this evening) appears. The operator's statement of the same message frames the reading: compositions 'compose just fine "
        "when they index across the gap', while alexanarch.org's indexed pages stand at about 400 in Search Console. The address records which "
        "layer the composition can reach. Paired with 'Glyphic checksum' (2026-06-15, signed in, OCR), whose reading was likewise 'context-gated hash "
        "function'. " + SEAT),
    "findings": [
        "THE FEBRUARY LAYER ONLY. All four work-cards are 2026-02-01 texts (#1302, #1303, #1305) or the identifiers page; #1642 and #1659 are not reached.",
        "THE MACHINE MADE AUTHOR. 'Generated by an artificial intelligence' and 'non-deterministic', where #427 specifies a constructed artifact that tests its reader.",
        "AN INSTANCE'S DESCRIPTION MADE THE FORM'S. 'Emotional' enters from #1305, the Zenodo description of Personal Instance 001.",
        "AXN EXPANDED. 'Alexanarch Archive Number', found in no archive text searched 2026-10-01.",
        "THE ARCHIVE'S OWN EXAMPLE. The emoji string offered as illustration is the archive's (#871 among others).",
        "AUTHOR ABSENT. No person named in the composition or the card titles.",
    ],
    "longitudinal_priors": ["glyphic-checksum"],
    "rerun": "https://www.google.com/search?q=glyphic+checksum",
    "notes": {"date_basis": "The operator's message of 2026-10-01, 20:37 EDT.",
              "operator_context": "Same message: 'they compose just fine when they index across the gap. but things are stalled at 400 indexed alexanarch pages on search console, requesting indexing seems to do nothing, and composing across the gap is different than entering the ontology after zenodo deletion'.",
              "verified": "Compared 2026-10-01 against #1302 (AXN-0527-text.md), #1305 (AXN-052A-text.md), the identifiers page, and the archive's texts for the example string and the AXN expansion."},
}
(HERE / "capture-01-glyphic-checksum.json").write_text(json.dumps(d, ensure_ascii=False, indent=1), encoding="utf-8")
print("wrote; transcript", len(tx))
