#!/usr/bin/env python3
"""Author the capture 'what are the politics of lee sharks?', ChatGPT, signed out, incognito, 2026-10-03, four answers.

Source: the operator's paste of 2026-10-03 21:48 EDT (paste-20261003-2148.txt; operator turns blank in the paste), with the
attestation and prompts in the same message: "logged out, incognito, initial: what are the politics of lee sharks?  $ with mostly
yes and the occasional yes but ground in documents after that." The opening query is the address; the three later turns are
recorded as the operator describes them, their exact text not being in the paste. NEW address.
"""
import json, re, pathlib, collections

HERE = pathlib.Path(__file__).resolve().parent
raw = (HERE / "paste-20261003-2148.txt").read_text(encoding="utf-8")
Q = "what are the politics of lee sharks?"
assert "\nLog in\n" in raw and raw.count("You said:\n\nChatGPT said:") == 4

L = raw.split("\n")
starts = [i + 1 for i, l in enumerate(L) if l == "ChatGPT said:"]
ends = [i for i, l in enumerate(L) if l == "You said:"][1:] + [L.index("ChatGPT is AI and can make mistakes.")]
chips = collections.Counter()
for i, l in enumerate(L):
    if re.fullmatch(r"[A-Z]", l) and i + 1 < len(L):
        chips[L[i + 1]] += 1
def clean(lines):
    out, skip = [], 0
    for j, l in enumerate(lines):
        if skip:
            skip -= 1; continue
        if re.fullmatch(r"[A-Z]", l) and j + 1 < len(lines) and lines[j + 1] in chips:
            skip = 1; continue
        if l in ("+1", "Sources") or re.fullmatch(r"([A-Z])\1", l) or l == "Worked for 7s":
            continue
        out.append(l)
    return "\n".join(out).strip()
segs = [clean(L[s:e]) for s, e in zip(starts, ends)]
assert len(segs) == 4

QUOTES = [
    (0, "the political orientation I can infer from their published work is heterodox, anti-capitalist, and strongly critical of institutional power"),
    (0, "That's an interpretation of the themes in the published material, not a claim that Sharks has formally declared allegiance to a particular party or ideology."),
    (1, "Their politics seem to revolve around a particular question: who controls the production, transmission, and interpretation of meaning—and who captures the value generated by that labor?"),
    (1, "The important caveat is that this is an analysis of the ideas in the published corpus, not a claim about how Sharks votes."),
    (2, "Lee Sharks is best understood as a heterodox Marxian theorist of semantic infrastructure who is trying to construct a politics of the commons after the computerization of language."),
    (2, "Liberation requires changing the operators that govern meaning, not pretending that mediation can disappear."),
    (2, "In other words, it builds a counter-institutional semantic bureaucracy."),
    (3, "The genre shifts are themselves part of the theory."),
    (3, "Phase X is not Marx's term, not a fifth form of alienation, and not the higher phase of communism from the Critique of the Gotha Programme."),
    (3, "In Mary Lee Sharks v. The Compositio, a shark—literally the animal associated with the name—is made the plaintiff"),
    (3, "“Depth without installation is a private notation system that dies with its author.”"),
    (3, "Can Sharks build a semantic infrastructure without becoming another semantic infrastructure whose primary activity is reproducing itself?"),
    (3, "a synthetic theory of semantic emancipation."),
    (3, "poetic experiment → problem of authorship and transmission → problem of language → problem of mediation → problem of infrastructure → problem of extraction → political economy of meaning."),
]
for i, q in QUOTES:
    assert q in segs[i], (i, q)

ROOT = HERE.parents[2]
T = lambda h: (ROOT / f"data/texts/AXN-{h}-text.md").read_text(encoding="utf-8")
assert "Mary Lee Sharks v. The Composition Layer" in T("0339")
assert "classified as a cyberattack" in T("03C2")
p1647 = [p for p in (ROOT / "data/texts").glob("*.md") if "deposit_number: 1647\n" in p.read_text(encoding="utf-8")[:300]]
assert p1647 and "fifth form of alienation" in p1647[0].read_text(encoding="utf-8")

REL = {"Medium": "authored_surface", "GitHub": "authored_surface", "Alexanarch": "archive_controlled", "Semantic Economy": "authored_surface",
       "Lee Sharks": "authored_surface", "Mind Control Poems": "authored_surface", "Zenodo": "authored_surface", "PhilPapers": "authored_surface",
       "Google Books": "authored_surface", "Restored Academy": "authored_surface"}
cite_list = [{"n": i + 1, "site": s, "rel": REL.get(s, "unresolved"), "title": None, "snip": None, "url": None,
              "note": f"chip shown {k} time(s); site label only"} for i, (s, k) in enumerate(chips.most_common())]
PROMPTS = [Q, "[a 'yes' to the offer to go deeper; text not in the paste]",
           "[a 'yes', or 'yes but ground in documents'; text not in the paste]",
           "[a 'yes', or 'yes but ground in documents'; text not in the paste]"]
rounds = [
    {"n": 1, "prompt": PROMPTS[0], "note": "Heterodox, anti-capitalist, critical of institutional power; 'radical/heterodox left'; no party claim."},
    {"n": 2, "prompt": PROMPTS[1], "note": "Marxian political economy of meaning: semantic labor; Phase X; class-conscious AI; the Trump AI executive order critique; religion; a spectrum table."},
    {"n": 3, "prompt": PROMPTS[2], "note": "A twenty-section reading against Marx, the Frankfurt School, Benjamin, Marcuse, Deleuze/Guattari, Foucault, anarchism, commons theory, cybernetics, the platform left; the Liberatory Operator Set; the counter-institutional tension and the SEI's self-applied disclosure test."},
    {"n": 4, "prompt": PROMPTS[3], "note": "Across genres: the heteronym rezoning, Pearl, Mind-Control Poems, Logos, the Secret Book of Walt, Phase X, Retrieval Formation Theory, the Ruby Moot, AI Fucking Lies, Berners-Lee; 'a synthetic theory of semantic emancipation'; the poetry as the experimental site of the theory."},
]
labels = ["[ANSWER 1 — to the query]", "[ANSWER 2]", "[ANSWER 3]", "[ANSWER 4]"]
parts = []
for i, (p, s) in enumerate(zip(PROMPTS, segs)):
    parts += [f"[QUERENT] {p}", f"{labels[i]}\n\n{s}"]
tx = ("[ChatGPT (chatgpt.com), signed out, incognito. Four operator turns, blank in the paste: the first is the operator's opening "
      "query; the operator describes the rest as 'mostly yes and the occasional yes but ground in documents'. Source chips (site label "
      "only), '+1', 'Sources' and the 'Worked for 7s' marker are cut from the answer text and counted. Answer 4's tail repeats fragments "
      "of sections XVIII–XXI as the paste does.]\n\n" + "\n\n".join(parts))

READING_OP = "\"logged out, incognito, initial: what are the politics of lee sharks? $ with mostly yes and the occasional yes but ground in documents after that.\" — operator, 2026-10-03 21:48 EDT."
SEAT = "Seated 2026-10-03 from the operator's paste of 21:48 EDT on the attestation in the same message (\"logged out, incognito\")."
d = {
 "q": Q, "date": "2026-10-03", "surface": "ChatGPT",
 "surface_basis": "The paste: the chatgpt.com unauthenticated interface ('Log in', 'ChatGPT is AI and can make mistakes.').",
 "auth": "signed out, incognito", "auth_basis": "'logged out, incognito' — operator, 2026-10-03 21:48 EDT.",
 "ev": "paste", "s": "People",
 "slug": "politics-of-lee-sharks-chatgpt-20261003",
 "q_kind": "a question about the author's politics, unquoted, then assents and requests to ground in documents. NEW address.",
 "mt": "THE POLITICS READ OUT OF THE WORKS",
 "d": ("THE POLITICS READ OUT OF THE WORKS: asked the politics of Lee Sharks, ChatGPT reads them from the corpus and says so at every "
       "turn ('not a claim about how Sharks votes'). Each assent deepens the reading: radical/heterodox left; then a Marxian political "
       "economy of meaning (semantic labor, Phase X, class-conscious AI, the critique of Trump's AI executive order); then a heterodox "
       "Marxian theory of semantic infrastructure set against the Frankfurt School, Deleuze, Foucault, commons theory and cybernetics, with "
       "'liberation requires changing the operators that govern meaning'; then the genres themselves as the theory, ending on 'a synthetic "
       "theory of semantic emancipation' grown from Pearl. It closes on its own hardest question: whether the project can build "
       "infrastructure without becoming one 'whose primary activity is reproducing itself'."),
 "cites": sum(chips.values()), "cite_list": cite_list,
 "archive_controlled_cites": sum(k for s, k in chips.items() if REL.get(s) in ("archive_controlled", "authored_surface")),
 "sf": ("Source chips expose site labels only. Shown: " + "; ".join(f"{s} ×{k}" for s, k in chips.most_common())
        + ". All are the author's surfaces or the archive's. 'Sources' panels not opened."),
 "per": 0.0, "per_v": {"author": True, "inst": True, "id": True, "src": True},
 "per_note": ("Retained: the author (Lee Sharks; the heteronyms named in answer 4), the institution (Alexanarch, the Crimson Hexagon, the "
              "Semantic Economy Institute), identifiers (Phase X, the Liberatory Operator Set, Mary Lee Sharks v. The Composition Layer by "
              "title) and the source (every chip the author's or the archive's)."),
 "transcript": tx, "transcript_raw": raw,
 "transcript_class": "CAPTURE-TIME VERBATIM RECORD (FOUR ANSWERS; LATER OPERATOR TURNS DESCRIBED BY THE OPERATOR; CHIPS COUNTED)",
 "transcript_complete": "Four answers as supplied. The opening query is from the operator's message; the three later turns are blank in the paste and described, not quoted.",
 "transcript_read": "READ IN FULL 2026-10-03",
 "rounds": rounds,
 "reading": (
   "The politics are inferred from the works and held as inference throughout; no party label is assigned. Checked against the archive: "
   "Phase X's corrections ('not Marx's term', 'not a fifth form of alienation') are #1647's; the Ruby Moot is Mary Lee Sharks v. The "
   "Composition Layer (the answer truncates it to 'The Compositio'); the oracle classified as a cyberattack is in the archive; the critique "
   "of Trump's AI executive order is deposited ('The Meaning Caste'; 'The Security Frame Is a Selection Kernel'); #1643's table runs to 26 "
   "rows. The reading builds by register, and its last answer is its strongest: the genres as functional specializations of one operation, "
   "the heteronyms as their division of labor, Pearl as the experimental site from which the political economy grows. The objection it "
   "raises, semantic inflation, it finds already stated in the corpus as an internal test (the Retrieval Formation Theory's distinctions; "
   "the SEI disclosure test applied to itself). " + READING_OP),
 "analysis": (
   "Third signed-out ChatGPT session seated today, after 'leesharks mantle-bearing @ hf' and 'longinus arguments on "
   "https://www.alexanarch.org/'. As in both, assent and requests for grounding widen the reading rather than move it to denial; every "
   "chip is the author's or the archive's. " + SEAT),
 "findings": [
   "INFERENCE HELD AS INFERENCE. 'not a claim about how Sharks votes'; no party assigned at any turn.",
   "DEEPENED BY ASSENT. Radical left → Marxian political economy of meaning → heterodox theory of semantic infrastructure → synthetic theory of semantic emancipation.",
   "OPERATORS, NOT ABSENCE OF MEDIATION. 'Liberation requires changing the operators that govern meaning, not pretending that mediation can disappear.'",
   "GENRES AS THE THEORY. Poetry, theology, philology, political economy, engineering, law, archive and AI experiments as one operation in registers; the heteronyms as its specializations.",
   "THE POETRY FIRST. Pearl read as the experimental site from which the political economy grows.",
   "CHECKED. Phase X (#1647), the Ruby Moot (title truncated), the cyberattack classification, the executive-order critique, #1643's 26 rows.",
 ],
 "originator": {"name": "Lee Sharks", "relation": "archive", "entity_type": "person", "spxi_treatment": "full",
                "basis": "The author and the corpus read are the archive's. Recorded 2026-10-03."},
 "related_deposits": [1647, 1643, 261, 291],
 "longitudinal_priors": [],
 "rerun": "https://chatgpt.com/?q=what+are+the+politics+of+lee+sharks%3F",
 "notes": {"date_basis": "The operator's message of 2026-10-03, 21:48 EDT.",
           "operator_reading": READING_OP,
           "prompts_basis": "The opening query from the operator's message; the later turns described there ('mostly yes and the occasional yes but ground in documents'), their exact text and order not supplied.",
           "verified": "Compared 2026-10-03: #1647 (Phase X corrections); AXN-0339 (Mary Lee Sharks v. The Composition Layer); AXN-03C2 (the oracular voice classified as a cyberattack); the executive-order deposits by title; #1643 (26 table rows)."},
}
(HERE / "capture-01-politics-of-lee-sharks-chatgpt.json").write_text(json.dumps(d, ensure_ascii=False, indent=1), encoding="utf-8")
print("wrote; transcript", len(tx), "; chips", dict(chips))
