#!/usr/bin/env python3
"""build_capture_records.py — one page per capture, one file per capture, and a table of contents.

WHY THIS EXISTS (2026-10-01)
A composition surface asked to inspect the registry reported: "Content length is too large: 4,194,305+ bytes".
Every route to a capture's content ran through a file past the fetch ceiling that composition surfaces use:
the gallery (8.4 MB), the registry JSON (11.8 MB), and every citation, because a citation was an anchor
(captures/#slug) inside the gallery and a fetcher drops the fragment and requests the whole page. The
address pages were small but carried no capture text. The registry was readable and could not be inspected.

Ruling (Lee Sharks, 2026-10-01, option b): the capture's own record page is its citation.

WHAT IT WRITES (all derived from data/EA-WG-CAPTURES-01.json; never hand-edit)
  captures/{slug}/index.html     the record page: the full card, record open, with the address page, the
                                 gallery anchor and the record's JSON linked. Largest record ~210 KB.
  captures/{slug}/record.json    the registry entry as stored, with its record URL.
  captures/{obs_slug}/index.html for an observation whose slug differs from its address's: a short page that
                                 states the observation and resolves to captures/{slug}/#{obs_slug}.
  captures/index.json            the table of contents: one row per capture, with every observation's URL
                                 and each record file's sha256. ~150 KB.
  sitemap-captures.xml           the record pages.

Deterministic: same registry, same bytes. Directories it no longer owns are removed only if they carry its
marker, so nothing else under captures/ is touched.

Usage:
    python3 scripts/build_capture_records.py           # write
    python3 scripts/build_capture_records.py --check   # fail if any output is missing or stale
"""
import argparse, hashlib, html, json, pathlib, re, shutil, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
REG = ROOT / "data/EA-WG-CAPTURES-01.json"
ADDR = ROOT / "data/semantic-addresses.json"
GALLERY = ROOT / "captures/index.html"
OUT = ROOT / "captures"
SITEMAP = ROOT / "sitemap-captures.xml"
BASE = "https://www.alexanarch.org"
MARK = "<!-- generated by scripts/build_capture_records.py -->"
esc = html.escape

import build_capture_gallery as G  # noqa: E402  card() renders the same card the gallery shows
from publish_semantic_addresses import resolve_collisions  # noqa: E402

try:
    from render_navbar import render_navbar  # type: ignore
except Exception:  # pragma: no cover
    def render_navbar():
        return '<nav class="nav"><a href="/">Alexanarch</a> <a href="/captures/">Captures</a></nav>'


def record_url(slug):
    return f"{BASE}/captures/{slug}/"


def jdump(o):
    return json.dumps(o, ensure_ascii=False, indent=1, sort_keys=False) + "\n"


def address_pages():
    """capture root slug -> /addresses/{page}/ , using the publisher's own slug resolution."""
    if not ADDR.exists():
        return {}
    addrs = json.loads(ADDR.read_text())["addresses"]
    slug_map = resolve_collisions(addrs)
    out = {}
    for k, a in addrs.items():
        for o in a.get("observations") or []:
            if o.get("source") == "mm-main-capture" and o.get("record_url"):
                root = o["record_url"].split("/captures/", 1)[1].split("/", 1)[0]
                out.setdefault(root, f"{BASE}/addresses/{slug_map[k]}/")
    return out


def gallery_style():
    m = re.search(r"<style[^>]*>.*?</style>", GALLERY.read_text(encoding="utf-8"), re.S)
    return m.group(0) if m else ""


COPY_JS = ("<script>document.addEventListener('click',function(ev){var b=ev.target.closest('[data-act]');"
           "if(!b||(b.dataset.act!=='cite'&&b.dataset.act!=='link'))return;ev.preventDefault();"
           "var t=b.dataset.act==='cite'?b.dataset.citation:b.dataset.cite;"
           "if(navigator.clipboard){navigator.clipboard.writeText(t).then(function(){var o=b.textContent;"
           "b.textContent='copied';setTimeout(function(){b.textContent=o},1200)})}});</script>")


def deposit_titles():
    """deposit number -> title, from the deposit registry, for the related-deposits line."""
    p = ROOT / "data/registry.json"
    if not p.exists():
        return {}
    return {d.get("deposit_number"): d.get("title") or "" for d in json.loads(p.read_text())["deposits"]}


def related_line(e, titles):
    nums = [n for n in (e.get("related_deposits") or []) if isinstance(n, int)]
    if not nums:
        return ""
    items = []
    for n in nums:
        t = titles.get(n, "")
        t = (t[:90] + "…") if len(t) > 90 else t
        items.append(f'<a href="/s/records/{n}/">#{n}</a>' + (f" {esc(t)}" if t else ""))
    return '<p class="sub" style="font-size:.85em">Related deposits: ' + " · ".join(items) + "</p>\n"


def page(e, reg, style, addr_url, titles=None):
    slug = e["slug"]
    q = e.get("q") or slug
    surf = ", ".join(e.get("surfaces") or [e.get("surface") or ""])
    dates = e.get("dates") or [e.get("date") or ""]
    span = dates[0] if len(dates) == 1 else f"{dates[0]} – {dates[-1]}"
    d = str(e.get("d") or "")
    url = record_url(slug)
    ld = {
        "@context": "https://schema.org", "@type": "CreativeWork",
        "name": f"«{q}» — {surf}, {span}", "url": url, "identifier": slug,
        "dateCreated": dates[0], "description": d[:600],
        "creator": {"@type": "Person", "name": "Lee Sharks", "identifier": "https://orcid.org/0009-0000-1599-0703"},
        "license": "https://creativecommons.org/licenses/by/4.0/",
        "isPartOf": {"@type": "Dataset", "name": "AI Overview Capture Registry (EA-WG-CAPTURES-01)",
                     "url": f"{BASE}/captures/", "version": reg.get("version")},
        "encoding": {"@type": "MediaObject", "encodingFormat": "application/json", "contentUrl": url + "record.json"},
    }
    links = [f'<a href="/captures/">the canonical Capture Registry</a> (version {esc(str(reg.get("version")))})',
             f'<a href="/captures/#{esc(slug)}">this card in the gallery</a>',
             f'<a href="record.json">this record as data</a>',
             '<a href="/captures/index.json">table of contents</a>']
    if addr_url:
        links.insert(1, f'<a href="{esc(addr_url)}">the address page</a>')
    rel = [n for n in (e.get("related_deposits") or []) if isinstance(n, int)]
    if rel:
        ld["mentions"] = [{"@type": "CreativeWork", "url": f"{BASE}/s/records/{n}/", "identifier": f"#{n}"} for n in rel]
    return (
        "<!doctype html>\n<html lang=\"en\"><head>\n" + MARK + "\n"
        '<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n'
        f"<title>{esc(q)} — {esc(surf)}, {esc(span)} — Capture Registry (EA-WG-CAPTURES-01)</title>\n"
        f'<meta name="description" content="{esc(d[:300])}">\n'
        f'<link rel="canonical" href="{url}">\n<link rel="cite-as" href="{url}">\n'
        f'<link rel="describedby" href="{url}record.json" type="application/json">\n'
        f'<link rel="collection" href="{BASE}/captures/">\n'
        f'<meta name="citation_title" content="{esc(q)}"><meta name="citation_author" content="Sharks, Lee">'
        f'<meta name="citation_date" content="{esc(dates[0])}"><meta name="citation_public_url" content="{url}">\n'
        '<script type="application/ld+json">' + json.dumps(ld, ensure_ascii=False) + "</script>\n"
        + style + "\n</head><body>\n" + render_navbar() + "\n"
        f'<p style="font-size:.85em;margin:10px 0 4px"><a href="/captures/">Capture Registry</a> › capture <code>{esc(slug)}</code></p>\n'
        f'<p class="sub" style="font-size:.85em">One record of the canonical Capture Registry (EA-WG-CAPTURES-01), '
        f'cited at <code>{url}</code>. ' + " · ".join(links) + ".</p>\n"
        + related_line(e, titles or {})
        + G.card(e, record=True) + "\n" + COPY_JS + "\n</body></html>\n")


def obs_page(e, o, reg):
    target = record_url(e["slug"]) + "#" + o["slug"]
    q = e.get("q") or e["slug"]
    return (
        "<!doctype html>\n<html lang=\"en\"><head>\n" + MARK + "\n"
        '<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n'
        f"<title>{esc(q)} — {esc(str(o.get('surface') or e.get('surface') or ''))}, {esc(str(o.get('date') or ''))} — Capture Registry (EA-WG-CAPTURES-01)</title>\n"
        f'<link rel="canonical" href="{record_url(e["slug"])}">\n'
        f'<meta http-equiv="refresh" content="0; url={esc(target)}">\n</head><body>\n'
        f'<p>Observation <code>{esc(o["slug"])}</code> of the address «{esc(q)}» — '
        f'{esc(str(o.get("surface") or e.get("surface") or ""))}, {esc(str(o.get("date") or ""))}. '
        f'Its record is on the address\'s page: <a href="{esc(target)}">{esc(target)}</a>.</p>\n'
        f'<p>{esc(str(o.get("d") or "")[:600])}</p>\n</body></html>\n')


def build():
    reg = json.loads(REG.read_text())
    entries = reg["entries"]
    style = gallery_style()
    addr = address_pages()
    titles = deposit_titles()
    files = {}
    toc = []
    for e in entries:
        slug = e["slug"]
        rec = dict(e)
        rec["record_url"] = record_url(slug)
        rj = jdump(rec)
        files[f"{slug}/record.json"] = rj
        files[f"{slug}/index.html"] = page(e, reg, style, addr.get(slug), titles)
        obs = []
        for o in e.get("observations") or []:
            os_ = o.get("slug") or slug
            obs.append({"slug": os_, "date": o.get("date"), "surface": o.get("surface") or e.get("surface"),
                        "auth": o.get("auth"),
                        "url": record_url(slug) + ("" if os_ == slug else f"#{os_}")})
            if os_ != slug:
                files[f"{os_}/index.html"] = obs_page(e, o, reg)
        toc.append({
            "slug": slug, "q": e.get("q"), "section": e.get("s"),
            "surfaces": e.get("surfaces") or [e.get("surface")], "dates": e.get("dates") or [e.get("date")],
            "n_observations": len(e.get("observations") or []) or 1,
            "status": e.get("mt"), "originator": (e.get("originator") or {}).get("relation"),
            "record_url": record_url(slug), "json_url": record_url(slug) + "record.json",
            "address_url": addr.get(slug),
            "sha256": hashlib.sha256(rj.encode()).hexdigest(),
            "observations": obs if len(obs) > 1 else None,
        })
    toc.sort(key=lambda r: r["slug"])
    n_obs = sum(r["n_observations"] for r in toc)
    files["index.json"] = jdump({
        "id": "EA-WG-CAPTURES-01", "title": "AI Overview Capture Registry — table of contents",
        "canonical": f"{BASE}/captures/", "version": reg.get("version"), "date": reg.get("date"),
        "addresses": len(toc), "observations": n_obs,
        "statement": ("The canonical, current Capture Registry. One row per address. Each record_url is the "
                      "capture's own page and its citation; json_url is the same record as data; an observation "
                      "is cited at its address's record_url with #observation_slug. The full registry in one file "
                      f"is {BASE}/data/EA-WG-CAPTURES-01.json (large). Supersedes every Zenodo release (v1.1–v8.3, "
                      "severed 2026-06-19)."),
        "record_form": f"{BASE}/captures/{{slug}}/", "json_form": f"{BASE}/captures/{{slug}}/record.json",
        "records": toc,
    })
    sm = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for r in toc:
        last = max(x for x in r["dates"] if x) if any(r["dates"]) else reg.get("date")
        sm.append(f"  <url><loc>{r['record_url']}</loc><lastmod>{last}</lastmod></url>")
    sm.append("</urlset>\n")
    return files, "\n".join(sm), len(toc), n_obs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    files, sitemap, n, n_obs = build()
    owned_dirs = {k.split("/", 1)[0] for k in files if "/" in k}
    stale = [k for k, v in files.items() if not (OUT / k).exists() or (OUT / k).read_text(encoding="utf-8") != v]
    orphans = [p.name for p in OUT.iterdir() if p.is_dir() and p.name not in owned_dirs
               and (p / "index.html").exists() and MARK in (p / "index.html").read_text(encoding="utf-8")[:400]]
    sm_stale = not SITEMAP.exists() or SITEMAP.read_text() != sitemap
    if a.check:
        bad = stale + orphans + (["sitemap-captures.xml"] if sm_stale else [])
        if bad:
            print(f"FAIL: {len(bad)} capture record output(s) missing or stale, e.g. {bad[:5]}", file=sys.stderr)
            return 1
        print(f"capture records current: {n} record pages, {n_obs} observations, table of contents, sitemap")
        return 0
    for k in stale:
        p = OUT / k
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(files[k], encoding="utf-8")
    for d in orphans:
        shutil.rmtree(OUT / d)
    if sm_stale:
        SITEMAP.write_text(sitemap)
    big = max(len(v.encode()) for v in files.values())
    print(f"capture records: {n} record pages, {sum(1 for k in files if k.endswith('index.html')) - n} observation "
          f"pages, table of contents ({len(files['index.json'].encode()):,} bytes); largest file {big:,} bytes; "
          f"{len(stale)} written, {len(orphans)} removed")
    if big > 4_000_000:
        print("FAIL: a record output exceeds 4 MB, the ceiling this script exists to stay under", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
