#!/usr/bin/env python3
"""build_record_api.py — one record, one GET: api/records/<n>.json for every deposit.

WHY (2026-08-15). An external audit of the archive's machine-retrieval layer
found one genuinely missing piece: an agent wanting ONE record must download the
multi-megabyte registry and filter it. Record pages carry full JSON-LD, but an
HTML page is not an API. This emits a per-record JSON projection so that
"understand record #1484" is a single request.

THE PROJECTION RULE (per the Data Atlas). These files are DERIVED, never
hand-edited: the registry entry is the canonical machine record and each file
here is that entry verbatim, plus computed URLs. A defect in an emitted file is
a defect in the registry or in this script — fix it there and re-emit. The
build is DETERMINISTIC: no timestamps, no environment, registry bytes in →
identical bytes out, so check_render_determinism-style double-builds compare
clean.

WHY NOT TOUCH THE HTML. The obvious companion change — rel=alternate links on
existing record pages — is DEFERRED, with the reason recorded: record pages
carry post-render surgical layers (the superseded-record retirement apparatus:
noindex, axn:retired, repointed canonicals, cite-instead banners) that the
renderer does not know about. A bulk re-render on 2026-08-15 was attempted on
ONE record as a test and stripped all of it. The atlas rule held: intake is
safe, repair is dangerous, and this script is pure intake.

Registered as regenerate_surfaces surface "record-api".
"""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "api" / "records"


def build(reg=None, verbose=True):
    if reg is None:
        reg = json.loads((ROOT / "data/registry.json").read_text())
    OUT.mkdir(parents=True, exist_ok=True)
    n_written = n_same = 0
    for d in reg["deposits"]:
        n = d["deposit_number"]
        rec = dict(d)  # the registry entry IS the record; project it whole
        rec["_projection"] = {
            "note": ("Derived file. Canonical machine record is this entry in data/registry.json; "
                     "the human record is the record_url. Do not edit this file."),
            "record_url": f"https://www.alexanarch.org/s/records/{n}/",
            "registry_url": "https://www.alexanarch.org/data/registry.json",
            "text_url": f"https://www.alexanarch.org/data/texts/AXN-{d['hex']}-text.md",
            "oai_pmh": "https://www.alexanarch.org/oai?verb=Identify",
        }
        blob = json.dumps(rec, indent=1, ensure_ascii=False, sort_keys=False) + "\n"
        p = OUT / f"{n}.json"
        if p.exists() and p.read_text() == blob:
            n_same += 1
            continue
        p.write_text(blob, encoding="utf-8")
        n_written += 1
    # prune projections for rolled-back deposits so the API never serves a ghost
    live = {str(d["deposit_number"]) for d in reg["deposits"]}
    pruned = 0
    for p in OUT.glob("*.json"):
        if p.stem not in live:
            p.unlink(); pruned += 1
    if verbose:
        print(f"record API: {n_written} written · {n_same} unchanged · {pruned} pruned · "
              f"{len(reg['deposits'])} total at api/records/<n>.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(build())
