#!/usr/bin/env python3
"""build_heteronym_index.py — project records/ into heteronyms.jsonl.

ONE CANONICAL STORE, ONE PROJECTION (dataflow atlas).

  datasets/heteronyms/records/*.json   CANONICAL. Twenty-six identity cards,
                                       mirrored to the live /who/ surfaces.
  datasets/heteronyms/heteronyms.jsonl PROJECTION. Generated by this script.

WHY THIS EXISTS. On 2026-08-15 an agent read heteronyms.jsonl, found Sparrow
Wells with roles ["dodecad D09"] and Sen Kuro with none, and recommended
against seating either as an editor "until their records are populated." Their
records WERE populated — richly — in records/, a layer the .jsonl gives no hint
of. The thin index was mistaken for the data, and the recommendation was wrong.

The fix is not to move the seat. heteronyms.jsonl is a published contract: the
datasets tab, MANIFEST.json, the README, the OAI remediation workplan and the
rhizome audit inventory all point at it. Reseating breaks consumers to solve a
problem that is not about seating.

The fix is that the projection carries the store's data and says what it is.
Every row is stamped _derived_from, so an agent reading a row learns where the
authority lives on the same line it is reading.

Usage:
  build_heteronym_index.py            regenerate the projection
  build_heteronym_index.py --check    fail if the projection has drifted
"""
import json, sys, pathlib, argparse

ROOT = pathlib.Path(__file__).resolve().parent.parent
RECORDS = ROOT / "datasets/heteronyms/records"
INDEX = ROOT / "datasets/heteronyms/heteronyms.jsonl"

# Keys the existing consumers already read. Preserved so nothing downstream breaks.
LEGACY = ["person_id", "name", "identity_type", "orthonym_relation", "roles", "domains",
          "voice_signature", "associated_terms", "institutional_affiliations", "active_period",
          "orcid", "notes", "dodecad_v1_1_position", "v1_1_role", "sep_2025", "avatar_paths",
          "reconciliation_note", "archive_default_position", "archive_role", "subcategory",
          "vital_status", "office_eligibility"]
# Keys that exist only in the cards and were invisible in the old thin index.
RICH = ["function", "domain", "institution", "rooms", "journal", "journal_seat", "office",
        "mantle", "ordinal", "het_id", "surface", "works", "traversal", "corpus_verified",
        "open_questions", "forward_library", "catalogue", "mmrs_role", "captures",
        "appearances", "works_of_record", "journal_seat", "vital_status",
        "captures_by_name", "is_position_not_occupant", "office_eligibility",
        "deposits_of_the_position", "claims"]


def load_existing():
    if not INDEX.exists():
        return {}
    out = {}
    for line in INDEX.read_text(encoding="utf-8").split("\n"):
        if line.strip():
            r = json.loads(line)
            out[r.get("name")] = r
    return out


def build():
    prior = load_existing()
    rows = []
    for p in sorted(RECORDS.glob("*.json")):
        card = json.loads(p.read_text(encoding="utf-8"))
        name = card.get("name")
        row = {}
        # legacy fields: card wins, prior index fills gaps (avatars, sep_2025 etc.
        # live only in the index and must not be dropped)
        for k in LEGACY:
            v = card.get(k, prior.get(name, {}).get(k))
            if v not in (None, [], {}, ""):
                row[k] = v
        row.setdefault("person_id", p.stem)
        row.setdefault("name", name)
        for k in RICH:
            if card.get(k) not in (None, [], {}, ""):
                row[k] = card[k]
        row["_derived_from"] = f"datasets/heteronyms/records/{p.name}"
        row["_authority"] = "records/ is canonical; this line is a projection. Edit the record, not this file."
        rows.append(row)
    # deterministic: Dodecad by position, then everyone else by name
    rows.sort(key=lambda r: (r.get("dodecad_v1_1_position") or 99, r.get("name") or ""))
    return "\n".join(json.dumps(r, ensure_ascii=False) for r in rows) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    new = build()
    if a.check:
        cur = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        if cur != new:
            print("FAIL: heteronyms.jsonl has drifted from records/.")
            print("  The projection is stale or was hand-edited. Run without --check.")
            return 1
        print(f"OK: projection matches records/ ({len(new.splitlines())} rows)")
        return 0
    INDEX.write_text(new, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(ROOT)} — {len(new.splitlines())} rows from {len(list(RECORDS.glob('*.json')))} records")
    return 0


if __name__ == "__main__":
    sys.exit(main())
