#!/usr/bin/env python3
"""
citation_extractor.py — extends data/citation-graph.json with edges discovered
by scanning deposit texts for AXN references, EA-* sovereign document IDs,
bare deposit-number references (#N), and (as a refresh of existing coverage)
Zenodo DOIs.

═══════════════════════════════════════════════════════════════════════════════
WHY THIS EXISTS
═══════════════════════════════════════════════════════════════════════════════

The current data/citation-graph.json was generated by pattern-matching legacy
Zenodo DOIs in deposit text. That mechanism worked when CHA deposits cited
each other by Zenodo DOI. After the 2026-06-19 termination, deposits cite
each other by AXN reference (full or hex-short) and by EA-* sovereign IDs.
1,692 of 1,710 edges (99%) are doi_resolution from the legacy mechanism;
citation aggregation effectively stops at deposit ~#766.

This extractor closes that gap by extracting the post-termination reference
patterns directly.

═══════════════════════════════════════════════════════════════════════════════
WHAT IT EXTRACTS
═══════════════════════════════════════════════════════════════════════════════

For each data/texts/AXN-<HEX>-text.md file (the source deposit):

  axn_reference      — full canonical AXN like "AXN:0379.GENERATIVE.⚙️🔍📜🏛️⚡🔄"
                       (resolved via registry.json's `axn` and `legacy_axn` fields)
  axn_hex_reference  — short AXN-<HEX> like "AXN-0371" (resolved via `hex` field)
  ea_id_reference    — sovereign document ID like "EA-MPAI-DOI-IMPERMANENCE-01"
                       (resolved via registry's `sovereign_id`, `document_id`,
                       and text-discovered EA-* IDs in titles/descriptions)
  deposit_number_reference — bare "#N" reference (resolved by direct lookup)
  doi_resolution     — Zenodo DOI "10.5281/zenodo.<N>"
                       (resolved via data/doi-resolution-index.json)

═══════════════════════════════════════════════════════════════════════════════
USAGE
═══════════════════════════════════════════════════════════════════════════════

    # Extract and append new edges to citation-graph.json
    python3 scripts/citation_extractor.py

    # Dry-run (just report what would change)
    python3 scripts/citation_extractor.py --dry-run

    # Restrict to deposit range (for testing)
    python3 scripts/citation_extractor.py --from 770 --to 879

The script is idempotent — re-running produces the same result. Existing
edges are preserved; only genuinely new (source, target, via) triples are
added. Self-references are skipped.
═══════════════════════════════════════════════════════════════════════════════
"""

import argparse
import json
import re
import sys
from pathlib import Path
from datetime import datetime, timezone

REPO_ROOT = Path(__file__).resolve().parent.parent

# Patterns used for extraction. Capture groups give the identifying token.
PAT_AXN_FULL = re.compile(r'AXN:[0-9A-F]{2,4}\.[A-Z]+\.[^\s\.\'",;<>\)]{1,16}')
PAT_AXN_HEX = re.compile(r'(?<![\w\-])AXN-([0-9A-F]{2,4})(?![0-9A-F])')
PAT_EA_ID = re.compile(r'(?<![\w\-])EA(?:-[A-Z]+){2,4}-\d+(?!\d)')
# Bare #N — must be preceded by whitespace, opening paren/bracket, comma, semicolon,
# em-dash, or be at start of line. Excludes URL fragments like ".../path#1-section".
PAT_DEPOSIT_NUM = re.compile(r'(?:^|(?<=[\s(\[,;—]))#(\d{1,4})(?!\d)', re.MULTILINE)
PAT_ZENODO_DOI = re.compile(r'10\.5281/zenodo\.(\d+)')


def build_resolvers(reg, doi_index):
    """Build the resolver maps from registry and doi-resolution-index."""
    axn_to_deposit = {}
    hex_to_deposit = {}
    ea_id_to_deposit = {}
    doi_to_deposit = {}
    deposit_num_set = set()

    for d in reg["deposits"]:
        n = d["deposit_number"]
        deposit_num_set.add(n)

        # Full AXN (canonical) and legacy
        axn = d.get("axn", "")
        if axn:
            axn_to_deposit[axn] = n
        legacy = d.get("legacy_axn", "")
        if legacy:
            axn_to_deposit[legacy] = n
        # Also map any AXN listed in axn_history
        for ah in d.get("axn_history", []):
            if isinstance(ah, dict) and ah.get("axn"):
                axn_to_deposit[ah["axn"]] = n

        # Hex label
        hex_label = d.get("hex", "")
        if hex_label:
            hex_to_deposit[hex_label.upper()] = n

        # EA-* sovereign IDs
        for field in ("sovereign_id", "document_id", "ea_id"):
            v = d.get(field, "")
            if v and v.startswith("EA-"):
                ea_id_to_deposit[v] = n
        # Also scan title and description for embedded EA-* IDs (often this is
        # how the deposit references itself for citation purposes)
        text_blob = (d.get("title", "") + " " + d.get("description", ""))
        for m in PAT_EA_ID.finditer(text_blob):
            ea_id = m.group(0)
            ea_id_to_deposit.setdefault(ea_id, n)

    # DOI map from doi-resolution-index.json. The actual field name in mappings
    # is `dead_doi` (the legacy Zenodo DOI that no longer resolves). The mapping
    # goes dead_doi → sovereign_id → deposit_number, so we need a sovereign_id
    # map from the registry to close the chain.
    sovereign_id_to_deposit = {}
    for d in reg["deposits"]:
        sid = d.get("sovereign_id")
        if sid:
            sovereign_id_to_deposit[sid] = d["deposit_number"]

    if isinstance(doi_index, dict):
        # Schema variant 1: {"mappings": [{"dead_doi": ..., "sovereign_id": ...}]}
        if "mappings" in doi_index and isinstance(doi_index["mappings"], list):
            for m in doi_index["mappings"]:
                if not isinstance(m, dict):
                    continue
                doi = m.get("dead_doi") or m.get("doi")
                if not doi:
                    continue
                dep_num = m.get("deposit_number") or m.get("alexanarch_deposit")
                if dep_num is None:
                    sid = m.get("sovereign_id")
                    dep_num = sovereign_id_to_deposit.get(sid) if sid else None
                if dep_num is not None:
                    doi_to_deposit[doi] = dep_num
        else:
            # Schema variant 2: keyed by doi
            for doi, entry in doi_index.items():
                if not isinstance(entry, dict):
                    continue
                dep_num = entry.get("deposit_number") or entry.get("alexanarch_deposit")
                if dep_num is None:
                    sid = entry.get("sovereign_id")
                    dep_num = sovereign_id_to_deposit.get(sid) if sid else None
                if dep_num is not None:
                    doi_to_deposit[doi] = dep_num

    return {
        "axn": axn_to_deposit,
        "hex": hex_to_deposit,
        "ea_id": ea_id_to_deposit,
        "doi": doi_to_deposit,
        "deposit_nums": deposit_num_set,
    }


def hex_to_deposit_from_filename(fname):
    """data/texts/AXN-<HEX>-text.md → HEX (uppercase)."""
    m = re.match(r"AXN-([0-9A-F]+)-text\.md", fname, re.IGNORECASE)
    return m.group(1).upper() if m else None


def extract_references(text, source_deposit, resolvers):
    """Extract all references from one deposit text. Returns list of
    (target_deposit_number, via, evidence_token) tuples, deduplicated within
    this source-deposit's text."""
    seen = set()  # (target_num, via) — dedup within this text
    out = []

    def emit(target, via, token):
        if target is None or target == source_deposit:
            return
        key = (target, via)
        if key in seen:
            return
        seen.add(key)
        out.append((target, via, token))

    for m in PAT_AXN_FULL.finditer(text):
        ref = m.group(0)
        if ref in resolvers["axn"]:
            emit(resolvers["axn"][ref], "axn_reference", ref)

    for m in PAT_AXN_HEX.finditer(text):
        hx = m.group(1).upper()
        if hx in resolvers["hex"]:
            emit(resolvers["hex"][hx], "axn_hex_reference", f"AXN-{hx}")

    for m in PAT_EA_ID.finditer(text):
        eid = m.group(0)
        if eid in resolvers["ea_id"]:
            emit(resolvers["ea_id"][eid], "ea_id_reference", eid)

    for m in PAT_DEPOSIT_NUM.finditer(text):
        n = int(m.group(1))
        if n in resolvers["deposit_nums"]:
            emit(n, "deposit_number_reference", f"#{n}")

    for m in PAT_ZENODO_DOI.finditer(text):
        full_doi = m.group(0)
        if full_doi in resolvers["doi"]:
            emit(resolvers["doi"][full_doi], "doi_resolution", full_doi)

    return out


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--dry-run", action="store_true",
                        help="report what would change; don't write")
    parser.add_argument("--from", dest="from_n", type=int,
                        help="only process deposits with deposit_number >= this")
    parser.add_argument("--to", dest="to_n", type=int,
                        help="only process deposits with deposit_number <= this")
    args = parser.parse_args()

    reg = json.load(open(REPO_ROOT / "data" / "registry.json"))
    doi_index = {}
    doi_path = REPO_ROOT / "data" / "doi-resolution-index.json"
    if doi_path.exists():
        doi_index = json.load(open(doi_path))

    resolvers = build_resolvers(reg, doi_index)
    print(f"Resolvers built:")
    print(f"  axn (canonical+legacy):  {len(resolvers['axn']):,}")
    print(f"  hex labels:              {len(resolvers['hex']):,}")
    print(f"  EA-* sovereign IDs:      {len(resolvers['ea_id']):,}")
    print(f"  Zenodo DOIs:             {len(resolvers['doi']):,}")
    print(f"  deposit numbers in set:  {len(resolvers['deposit_nums']):,}")
    print()

    # Map hex → deposit_number for resolving filenames
    hex_to_num = {d["hex"].upper(): d["deposit_number"] for d in reg["deposits"] if d.get("hex")}

    cg_path = REPO_ROOT / "data" / "citation-graph.json"
    cg = json.load(open(cg_path))
    existing_edges = cg.get("edges", [])
    # Build a set of existing (source, target, via) triples
    existing_keys = set()
    for e in existing_edges:
        existing_keys.add((e.get("source_deposit"), e.get("target_deposit"), e.get("via")))

    new_edges = []
    texts_dir = REPO_ROOT / "data" / "texts"
    text_files = sorted(texts_dir.glob("AXN-*-text.md"))

    processed = 0
    matched_files = 0
    skipped_unresolvable = 0

    for tf in text_files:
        hex_label = hex_to_deposit_from_filename(tf.name)
        if not hex_label:
            continue
        source_num = hex_to_num.get(hex_label)
        if not source_num:
            skipped_unresolvable += 1
            continue
        if args.from_n is not None and source_num < args.from_n:
            continue
        if args.to_n is not None and source_num > args.to_n:
            continue

        processed += 1
        text = tf.read_text(encoding="utf-8")
        refs = extract_references(text, source_num, resolvers)

        # Build canonical source_axn for the edges
        source_d = next((d for d in reg["deposits"] if d["deposit_number"] == source_num), None)
        source_axn = source_d.get("axn") if source_d else None

        for target_num, via, token in refs:
            key = (source_num, target_num, via)
            if key in existing_keys:
                continue
            target_d = next((d for d in reg["deposits"] if d["deposit_number"] == target_num), None)
            target_axn = target_d.get("axn") if target_d else None
            edge = {
                "source_deposit": source_num,
                "source_axn": source_axn,
                "target_deposit": target_num,
                "target_axn": target_axn,
                "via": via,
                "evidence_token": token,
                "extracted_by": "citation_extractor.py",
            }
            new_edges.append(edge)
            existing_keys.add(key)
        if refs:
            matched_files += 1

    print(f"Deposit texts processed: {processed}")
    print(f"Texts with extractable refs: {matched_files}")
    if skipped_unresolvable:
        print(f"Texts skipped (could not resolve source deposit): {skipped_unresolvable}")
    print(f"New edges discovered: {len(new_edges):,}")
    print()

    # Summarize new edges by via type
    from collections import Counter
    via_counts = Counter(e["via"] for e in new_edges)
    print("New edges by via type:")
    for v, n in via_counts.most_common():
        print(f"  {v}: {n}")
    print()

    if args.dry_run:
        # Show samples
        print("Sample new edges (first 6):")
        for e in new_edges[:6]:
            print(f"  #{e['source_deposit']:4d} → #{e['target_deposit']:4d}  ({e['via']:28s}  token={e['evidence_token']})")
        print()
        print("[DRY RUN] No changes written.")
        return

    if not new_edges:
        print("No new edges to add.")
        return

    # Append edges, update totals, write back
    all_edges = existing_edges + new_edges
    cg["edges"] = all_edges
    cg["total_edges"] = len(all_edges)
    cg["total_deposits_citing"] = len(set(e["source_deposit"] for e in all_edges))
    cg["total_deposits_cited"] = len(set(e["target_deposit"] for e in all_edges))
    cg["dateModified"] = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    cg["description"] = (
        "Internal CHA / Alexanarch citation graph. Edges extracted from deposit "
        "texts via five mechanisms: doi_resolution (legacy Zenodo DOI patterns), "
        "axn_reference (full canonical AXN), axn_hex_reference (AXN-<HEX> short form), "
        "ea_id_reference (sovereign EA-* document IDs), deposit_number_reference (bare #N). "
        "Generated by scripts/citation_extractor.py — see /api/enrichment-protocol.json."
    )

    # Rebuild cited_by index
    cited_by = {}
    for e in all_edges:
        tgt = e["target_deposit"]
        cited_by.setdefault(str(tgt), []).append(e["source_deposit"])
    # Deduplicate
    for k in cited_by:
        cited_by[k] = sorted(set(cited_by[k]))
    cg["cited_by"] = cited_by

    with open(cg_path, "w", encoding="utf-8") as f:
        json.dump(cg, f, ensure_ascii=False, indent=2)

    print(f"✓ Wrote {len(new_edges)} new edges to {cg_path.name}")
    print(f"  Total edges now: {cg['total_edges']:,}")
    print(f"  Citing deposits: {cg['total_deposits_citing']:,}")
    print(f"  Cited deposits:  {cg['total_deposits_cited']:,}")


if __name__ == "__main__":
    main()
