#!/usr/bin/env python3
"""generate_state.py — produce data/state.json from actual data files.

This is the canonical, generated source for all counts and corpus statistics.
The hand-maintained counts in api/index.json, datasets/index.html, manifest/,
and similar surfaces have drifted historically. This file makes them
authoritative again: every surface that displays a count must read from
data/state.json (either at build time or at runtime via JS).

Run this whenever any underlying data file changes. Called automatically
by scripts/regenerate_surfaces.py.
"""
import hashlib
import json
import os
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def file_sha256(path: Path) -> str:
    """Return the SHA-256 hex digest of a file's bytes."""
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(65536), b''):
            h.update(chunk)
    return h.hexdigest()


def file_info(rel_path: str) -> dict:
    """Return existence, size, sha256 for a file relative to repo root."""
    p = ROOT / rel_path
    if not p.exists():
        return {'exists': False, 'path': rel_path}
    return {
        'exists': True,
        'path': rel_path,
        'size_bytes': p.stat().st_size,
        'sha256': file_sha256(p),
    }


def build_state() -> dict:
    """Read every data source that drives a displayed count, then emit the
    canonical state.json document."""
    registry_path = ROOT / 'data' / 'registry.json'
    with open(registry_path) as f:
        reg = json.load(f)
    deposits = reg.get('deposits', [])

    # Deposit status breakdown (from lifecycle protocol vocabulary)
    status_counts = {'ACTIVE': 0, 'SUPERSEDED': 0, 'WITHDRAWN': 0, 'DRAFT_PENDING': 0, 'METADATA_ONLY': 0}
    for d in deposits:
        s = d.get('status', 'ACTIVE')
        status_counts[s] = status_counts.get(s, 0) + 1

    # Series taxonomy
    series_ids = set()
    for d in deposits:
        sid = d.get('version_series_id')
        if sid:
            series_ids.add(sid)

    # Entity index
    eidx_path = ROOT / 'data' / 'entity-index.json'
    concept_count = 0
    if eidx_path.exists():
        with open(eidx_path) as f:
            eidx = json.load(f)
        concept_count = len(eidx.get('concepts', {}))

    # DOI resolution index
    doi_path = ROOT / 'data' / 'doi-resolution-index.json'
    doi_count = 0
    if doi_path.exists():
        with open(doi_path) as f:
            doi_data = json.load(f)
        # doi-resolution-index.json structure: top-level "doi_mappings" list, or similar
        if isinstance(doi_data, dict):
            for key in ('doi_mappings', 'mappings', 'doi_to_axn'):
                if key in doi_data:
                    v = doi_data[key]
                    doi_count = len(v) if isinstance(v, (list, dict)) else 0
                    break

    # Capture registry
    captures_path = ROOT / 'data' / 'EA-WG-CAPTURES-01-v8.3.json'
    capture_count = 0
    if captures_path.exists():
        with open(captures_path) as f:
            cap_data = json.load(f)
        if isinstance(cap_data, dict):
            capture_count = cap_data.get('total_captures', 0) or len(cap_data.get('captures', []))

    # Chunks
    chunks_index_path = ROOT / 'data' / 'chunks' / 'registry' / '_index.json'
    chunk_count = 0
    if chunks_index_path.exists():
        with open(chunks_index_path) as f:
            ci = json.load(f)
        chunk_count = len(ci.get('chunks', []))

    # Wiki entries (deposits with wiki_article populated)
    wiki_entries = sum(1 for d in deposits if (d.get('wiki_article') or '').strip())

    # Git commit (best-effort)
    git_head = None
    head_path = ROOT / '.git' / 'HEAD'
    if head_path.exists():
        try:
            with open(head_path) as f:
                ref = f.read().strip()
            if ref.startswith('ref: '):
                ref_path = ROOT / '.git' / ref[5:]
                if ref_path.exists():
                    with open(ref_path) as f:
                        git_head = f.read().strip()
            else:
                git_head = ref
        except Exception:
            pass

    state = {
        'schema_version': 'v1.0',
        'purpose': 'Single source of truth for all displayed counts. Generated by scripts/generate_state.py from data/registry.json and related data files. Never hand-maintain values here. All hand-written surfaces (api/index.json, datasets/, manifest/, etc.) should read from this file.',
        'generated_at': datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
        'source_commit': git_head,
        'deposits': {
            'total': len(deposits),
            'by_status': status_counts,
            'series_count': len(series_ids),
            'wiki_entries': wiki_entries,
        },
        'corpus': {
            'concepts_indexed': concept_count,
            'doi_resolutions': doi_count,
            'captures': capture_count,
            'chunks': chunk_count,
        },
        'data_files': {
            'registry': file_info('data/registry.json'),
            'entity_index': file_info('data/entity-index.json'),
            'doi_resolution_index': file_info('data/doi-resolution-index.json'),
            'capture_registry': file_info('data/EA-WG-CAPTURES-01-v8.3.json'),
            'navigation': file_info('data/navigation.json'),
            'browse_index': file_info('data/browse-index.json'),
        },
        'protocols': {
            'deposit': file_info('api/deposit-protocol.json'),
            'axn': file_info('api/axn-protocol.json'),
            'enrichment': file_info('api/enrichment-protocol.json'),
            'lifecycle': file_info('api/lifecycle-protocol.json'),
            'deposit_schema': file_info('api/deposit-schema.json'),
        },
        'consumed_by': [
            'api/index.json (counts under registries.deposits.current_count etc.)',
            'datasets/index.html (corpus stats)',
            'manifest/index.html (architectural claims)',
            'index.html noscript fallback (recent deposits)',
            'scripts/regenerate_surfaces.py (counts in browse/wiki headers)',
        ],
    }
    return state


def main():
    state = build_state()
    out_path = ROOT / 'data' / 'state.json'
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(state, f, indent=2, ensure_ascii=False)
        f.write('\n')
    print(f'  ✓ data/state.json (deposits.total={state["deposits"]["total"]}, '
          f'chunks={state["corpus"]["chunks"]}, captures={state["corpus"]["captures"]})')


if __name__ == '__main__':
    main()
